# Generated by Django 4.1.5 on 2023-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.toiimg.com%2Fthumb%2F56933159.cms%3Fimgsize%3D686279%26width%3D800%26height%3D800&imgrefurl=https%3A%2F%2Frecipes.timesofindia.com%2Frecipes%2Fpizza%2Frs56933159.cms&tbnid=kPaYLuwKlpxzTM&vet=12ahUKEwjRhqWuwOX8AhUknicCHWvnCq4QMygBegUIARCBAg..i&docid=qjbtW8wcuJEy4M&w=800&h=800&q=pizza&ved=2ahUKEwjRhqWuwOX8AhUknicCHWvnCq4QMygBegUIARCBAg', max_length=500),
        ),
    ]
