# Generated by Django 4.1.5 on 2023-02-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodz', '0002_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='http://3.bp.blogspot.com/-6C8L0SXuSHY/T-wlfd9dFJI/AAAAAAAAACg/ILqUp67tJTE/s1600/Fruits.jpg', max_length=500),
        ),
    ]
